on:
  workflow_dispatch:
  pull_request:
  push:

name: API Deployment

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dagger

    steps:

      - uses: actions/checkout@v2

      - name: Go Build Dagger
        run: go build

      - name: Dagger Test
        run: ./dagger test
      
      - name: Dagger Terraform
        run: ./dagger tf apply
        
      - name: Dagger Deploy API
        run: ./dagger deploy
