on:
  workflow_dispatch:
  pull_request:
  push:

name: API Deployment

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dagger

    steps:

      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "${{ secrets.DAGGER_ENV }}" > .env

      - name: Go Build Dagger
        run: go build

      - name: Dagger Pipeline
        run: ./dagger pipeline
